<?php

/*********************************************************************
* Extension configuration file for ext "linktypeswitch".
*
* Generated by ext 13-04-2014 12:04 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Link type switch / error handling',
  'description' => 'Allows config of different link types (e.g. to access restricted pages), improved error handling and redirect to login page.',
  'category' => 'fe',
  'shy' => 1,
  'dependencies' => '',
  'conflicts' => '',
  'priority' => '',
  'loadOrder' => '',
  'module' => '',
  'state' => 'alpha',
  'internal' => 0,
  'uploadfolder' => 0,
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'author' => 'Alexander Stehlik',
  'author_email' => 'alexander.stehlik.deleteme@gmail.com',
  'CGLcompliance' => '',
  'CGLcompliance_note' => '',
  'version' => '0.0.1',
  '_md5_values_when_last_written' => '',
  'constraints' => 
  array (
    'depends' => 
    array (
      'php' => '5.3.0-5.5.99',
      'typo3' => '6.2.0-6.3.99',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  'suggests' => 
  array (
  ),
  'comment' => 'Initial release',
  'user' => 'astehlik',
);

?>